version: "3.9"

services:
  backend:
    build:
      context: .
      dockerfile: ./docker/Dockerfile
    command: poetry run gunicorn app.main:app -b 0.0.0.0:8000 -k uvicorn.workers.UvicornWorker
    container_name: backend
    # depends_on:
    env_file: .env
    expose:
      - 8000
    volumes:
      - .:/app

  nginx:
    image: nginx:1.23.1
    container_name: nginx
    depends_on:
      - backend
    ports:
      - 80:80
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
