export const provincias = [
  { value: "Distrito Nacional", label: "Distrito Nacional" },
  { value: "Santo Domingo", label: "Santo Domingo" },
  { value: "Azua", label: "Azua" },
  { value: "Baoruco", label: "Baoruco" },
  { value: "Barahona", label: "Barahona" },
  { value: "Dajabón", label: "Dajabón" },
  { value: "Duarte", label: "Duarte" },
  { value: "El Seibo", label: "El Seibo" },
  { value: "Elías Piña", label: "Elías Piña" },
  { value: "Espaillat", label: "Espaillat" },
  { value: "Hato Mayor", label: "Hato Mayor" },
  { value: "Hermanas Mirabal", label: "Hermanas Mirabal" },
  { value: "Independencia", label: "Independencia" },
  { value: "La Altagracia", label: "La Altagracia" },
  { value: "La Romana", label: "La Romana" },
  { value: "La Vega", label: "La Vega" },
  { value: "María Trinidad Sánchez", label: "María Trinidad Sánchez" },
  { value: "Monseñor Nouel", label: "Monseñor Nouel" },
  { value: "Monte Cristi", label: "Monte Cristi" },
  { value: "Monte Plata", label: "Monte Plata" },
  { value: "Pedernales", label: "Pedernales" },
  { value: "Peravia", label: "Peravia" },
  { value: "Puerto Plata", label: "Puerto Plata" },
  { value: "Samaná", label: "Samaná" },
  { value: "San Cristóbal", label: "San Cristóbal" },
  { value: "San José de Ocoa", label: "San José de Ocoa" },
  { value: "San Juan", label: "San Juan" },
  { value: "San Pedro de Macorís", label: "San Pedro de Macorís" },
  { value: "Sánchez Ramírez", label: "Sánchez Ramírez" },
  { value: "Santiago", label: "Santiago" },
  { value: "Santiago Rodríguez", label: "Santiago Rodríguez" },
  { value: "Valverde", label: "Valverde" },
];

export const colors = [
  "red",
  "blue",
  "brown",
  "burlywood",
  "cadetblue",
  "chocolate",
  "coral",
  "crimson",
  "cyan",
  "darkblue",
  "darkorange",
  "darkred",
  "dodgerblue",
  "forestgreen",
  "grey",
  "hotpink",
  "indigo",
  "lawngreen",
  "lightpink",
  "limegreen",
  "magenta",
  "midnightblue",
  "orangered",
  "orchid",
  "palegreen",
  "paleturquoise",
  "royalblue",
  "salmon",
  "skyblue",
  "springgreen",
  "tomato",
  "violet",
];
