export const provincias = [
  { value: "Distrito Nacional", label: "Distrito Nacional" },
  { value: "Santo Domingo", label: "Santo Domingo" },
  { value: "Azua", label: "Azua" },
  { value: "Baoruco", label: "Baoruco" },
  { value: "Barahona", label: "Barahona" },
  { value: "Dajabón", label: "Dajabón" },
  { value: "Duarte", label: "Duarte" },
  { value: "El Seibo", label: "El Seibo" },
  { value: "Elías Piña", label: "Elías Piña" },
  { value: "Espaillat", label: "Espaillat" },
  { value: "Hato Mayor", label: "Hato Mayor" },
  { value: "Hermanas Mirabal", label: "Hermanas Mirabal" },
  { value: "Independencia", label: "Independencia" },
  { value: "La Altagracia", label: "La Altagracia" },
  { value: "La Romana", label: "La Romana" },
  { value: "La Vega", label: "La Vega" },
  { value: "María Trinidad Sánchez", label: "María Trinidad Sánchez" },
  { value: "Monseñor Nouel", label: "Monseñor Nouel" },
  { value: "Monte Cristi", label: "Monte Cristi" },
  { value: "Monte Plata", label: "Monte Plata" },
  { value: "Pedernales", label: "Pedernales" },
  { value: "Peravia", label: "Peravia" },
  { value: "Puerto Plata", label: "Puerto Plata" },
  { value: "Samaná", label: "Samaná" },
  { value: "San Cristóbal", label: "San Cristóbal" },
  { value: "San José de Ocoa", label: "San José de Ocoa" },
  { value: "San Juan", label: "San Juan" },
  { value: "San Pedro de Macorís", label: "San Pedro de Macorís" },
  { value: "Sánchez Ramírez", label: "Sánchez Ramírez" },
  { value: "Santiago", label: "Santiago" },
  { value: "Santiago Rodríguez", label: "Santiago Rodríguez" },
  { value: "Valverde", label: "Valverde" },
];

export const colors = [
  "#1F77B4",
  "#FF7F0E",
  "#2CA02C",
  "#D62728",
  "#9467BD",
  "#8C564B",
  "#E377C2",
  "#7F7F7F",
  "#BCBD22",
  "#17BECF",
  "#AEC7E8",
  "#FFBB78",
  "#98DF8A",
  "#FF9896",
  "#C5B0D5",
  "#C49C94",
  "#F7B6D2",
  "#C7C7C7",
  "#DBDB8D",
  "#9EDAE5",
  "#FFED6F",
  "#B5CF6B",
  "#FFC48C",
  "#A8DBA8",
  "#79BD9A",
  "#3B8686",
  "#0B486B",
  "#004D40",
  "#CFF09E",
  "#A3A500",
  "#F0E442",
  "#6D904F",
  "#66C2A4",
  "#FC8D62",
  "#8DA0CB",
];
